Repository slothy-optimizer/slothy, pull requests merged in 2024-04, with the labels that each got.

#50 Make the renaming of reserved registers configurable
  slothy/core/config.py
  slothy/targets/aarch64/aarch64_neon.py
Labels: enhancement

#53 Add support for vmull2, ngc xzr sbcs xzrs, sbcs xzrs and cmn
  slothy/targets/aarch64/aarch64_neon.py
  slothy/targets/aarch64/cortex_a55.py
  slothy/targets/aarch64/neoverse_n1_experimental.py
Labels: enhancement, needs-ci

#54 Support more variants of adcs and cmp with xzr
  slothy/targets/aarch64/aarch64_neon.py
  slothy/targets/aarch64/cortex_a55.py
Labels: needs-ci
